# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1 # since the e2e tests creates and deletes components, can only run the tests sequentially
      matrix:
        node-version: [12.x, 14.x]

    env:  # set environment variables for test suite
      IAM_API_KEY: ${{ secrets.IAM_API_KEY }}
      IBP_SERVICE_INSTANCE_URL: ${{ secrets.IBP_SERVICE_INSTANCE_URL }}
      DONOR_CA_STR: ${{ secrets.DONOR_CA_STR }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: npm run test         # unit tests
    - run: npm run test_e2e     # end to end tests, sequential
    - run: npm audit --production
