# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    env:  # set environment variables for test suite
      TEST: ${{ secrets.TEST }}
      TEST2: AnotherTest
      IAM_API_KEY: ${{ secrets.IAM_API_KEY }}
      IBP_SERVICE_INSTANCE_URL: ${{ secrets.IBP_SERVICE_INSTANCE_URL }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --production
    - run: npm run build
    - run: npm test         # unit tests
    #- run: npm test_e2e     # end to end tests, sequential
    - run: npm audit --production
